services:
  - type: web
    name: hostonews-php
    env: docker
    repo: https://github.com/debady/hostonews-tv.git
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
